name: Test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write

jobs:
  main:
    name: Linux (${{ matrix.working_directory }}, ${{ matrix.elixir }}, ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working_directory: ["nx", "exla", "torchx"]
        elixir: ["1.15.4", "1.16.2"]
        otp: ["25.3"]
        include:
          - elixir: "1.16.2"
            lint: true
    defaults:
      run:
        working-directory: ${{ matrix.working_directory }}
    env:
      MIX_ENV: test
      XLA_FLAGS: --xla_force_host_platform_device_count=2
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Retrieve dependencies cache
        env:
          cache-name: cache-mix-deps
        uses: actions/cache@v3
        id: mix-cache # id to use in retrieve action
        with:
          path: ${{ github.workspace }}/${{ matrix.working_directory }}/deps
          key: ${{ runner.os }}-Elixir-v${{ matrix.elixir }}-OTP-${{ matrix.otp }}-${{ hashFiles(format('{0}/{1}/mix.lock', github.workspace, matrix.working_directory)) }}-v1
      - name: Install dependencies
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}
        run: mix deps.get
      - name: Compile and check warnings
        run: mix compile --warnings-as-errors
      - name: Check formatting
        if: ${{ matrix.lint }}
        run: mix format --check-formatted
      - name: Submit Mix Dependencies
        uses: erlef/mix-dependency-submission@v1
